baseurl = "http://wiki.aotxland.com/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  authorName = "Yif"
  # for RSS feed filter https://gohugo.io/functions/where/#mainsections
  mainSections = ["post", "note", "docs"]
  pageBundle = true

[languages]
  [languages.en]
    title = "aotxland/WebNote"
    subtitle = "A Hugo Web Notebook"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "aotxland/WebNote"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[markup.highlight]
  noClasses = false