baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  favicon = "favicon/favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false
  authorName = "Yif"
  # for RSS feed filter https://gohugo.io/functions/where/#mainsections
  mainSections = ["post", "note", "docs"]
  #pageBundle = true

[languages]
  [languages.en]
    languageName = "English"
    title = "aotxland/WebNote"
    subtitle = "A Web Notebook for aotxland"
    owner = "Yif"
    keywords = ""
    copyright = "Yif"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "aotxland/WebNote"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "index"
        name = "Note首页"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "mainSite"
        name = "主站"
        url = "https://aotxland.com"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[author]
    name = "Yif"

[markup.highlight]
  noClasses = false